name: Qodo Cover
description: "Gets the diff of a PR, posts it as a comment, checks out the PR branch, and counts lines of code."
author: QodoAI

inputs:
  greeting:
    description: "Custom greeting message for the PR comment"
    required: false
    default: "Hello"
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get included files
      uses: actions/checkout@v3
      with:
        repository: qododavid/capa
        path: /tmp/capa
        ref: v1
        fetch-depth: 0

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get PR Diff
      run: |
        gh pr diff ${{ github.event.pull_request.number }} > /tmp/pr_diff.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Install Jinja2 CLI
      run: |
        pip install jinja2-cli
      shell: bash

    - name: Populate PR Comment with Jinja2
      run: |
        jinja2 /tmp/capa/.github/actions/qodo-cover/comment_template.j2 -D greeting="${{ inputs.greeting }}" -D diff="$(cat /tmp/pr_diff.txt)" > /tmp/comment_body.txt
      shell: bash

    - name: Post PR Diff Comment
      run: |
        gh pr comment ${{ github.event.pull_request.number }} -F /tmp/comment_body.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Count Lines of Code
      run: |
        find . -type f -name "*.py" -exec wc -l {} + | awk '{total += $1} END {print "Total lines of code:", total}'
      shell: bash