name: Qodo Cover
description: "Gets the diff of a PR, posts it as a comment, checks out the PR branch, and counts lines of code."
author: QodoAI

inputs:
  greeting:
    description: "Custom greeting message for the PR comment"
    required: false
    default: "Hello"
  github_token:
    description: "GitHub token for authentication"
    required: true
  project_language:
    description: "Language of the project"
    required: false
    default: "python"
  project_root:
    description: "Root directory of the project"
    required: false
    default: "."
  code_coverage_report_path:
    description: "Path to the coverage.xml"
    required: false
    default: "./coverage.xml"
  test_command:
    description: "Command to run tests, e.g. 'pytest --cov=. --cov-report=xml --cov-report=term'"
    required: true
  model:
    description: "LLM model name, e.g. 'gpt-4o'"
    required: false
    default: "gpt-4o"

runs:
  using: "composite"
  steps:

    - name: Install wget
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
      shell: bash

    - name: Download cover-agent-pro to /tmp/bin/
      run: ${{ github.action_path}}/scripts/download_binary.sh
      shell: bash

    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install jedi-language-server
      run: |
        pip install jedi-language-server
      shell: bash

    - name: Configure Git Identity
      run: |
        git config --global user.email "cover-bot@qodo.ai"
        git config --global user.name "Qodo Cover"
      shell: bash

    - name: Compute current timestamp
      id: timestamp
      run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV
      shell: bash

    - name: Get PR Diff
      run: |
        gh pr diff ${{ github.event.pull_request.number }} > /tmp/pr_diff.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Install Jinja2 CLI
      run: |
        pip install jinja2-cli
      shell: bash

    - name: Populate PR Comment with Jinja2
      run: |
        jinja2 ${{ github.action_path }}/comment_template.j2 -D greeting="${{ inputs.greeting }}" -D diff="$(cat /tmp/pr_diff.txt)" > /tmp/comment_body.txt
      shell: bash

    # - name: Post PR Diff Comment
    #   run: |
    #     gh pr comment ${{ github.event.pull_request.number }} -F /tmp/comment_body.txt
    #   env:
    #     GITHUB_TOKEN: ${{ inputs.github_token }}
    #   shell: bash

    - name: Run cover-agent-pro
      run: |
        /tmp/bin/cover-agent-pro \
          --project-language ${{ inputs.project_language }} \
          --project-root ${{ github.workspace }}/${{ inputs.project_root }} \
          --code-coverage-report-path ${{ github.workspace }}/${{ inputs.code_coverage_report_path }} \
          --test-command "${{ inputs.test_command }}" \
          --model ${{ inputs.model }}
      env:
        <<: ${{ toJSON(env) }}
      shell: bash

    - name: Check if files were modified
      id: check_modifications
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "files_modified=true" >> $GITHUB_ENV
        else
          echo "files_modified=false" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Commit changes if modified
      if: env.files_modified == 'true'
      run: |
        git add .
        git commit -m "add tests"
      shell: bash

    - name: Create a new branch
      if: env.files_modified == 'true'
      run: |
        git checkout -b qodo-cover-${{ github.event.pull_request.number }}-${{ env.timestamp }}
      shell: bash

    - name: Push the branch
      if: env.files_modified == 'true'
      run: |
        git push origin qodo-cover-${{ github.event.pull_request.number }}-${{ env.timestamp }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Create a PR from the new branch
      if: env.files_modified == 'true'
      run: |
        gh pr create --base ${{ github.event.pull_request.head.ref }} \
                     --head qodo-cover-${{ github.event.pull_request.number }}-${{ env.timestamp }} \
                     --title "Qodo Cover Update: ${{ env.timestamp }}" \
                     --body "Patch on #${{ github.event.pull_request.number }}: this PR adds tests generated by Qodo Cover."
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
