name: Qodo Cover
description: "Runs the Qodo Cover agent to generate tests."
author: QodoAI

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  project_language:
    description: "Language of the project"
    required: false
    default: "python"
  project_root:
    description: "Root directory of the project"
    required: false
    default: "."
  code_coverage_report_path:
    description: "Path to the coverage.xml"
    required: false
    default: "./coverage.xml"
  test_command:
    description: "Command to run tests, e.g. 'pytest --cov=. --cov-report=xml --cov-report=term'"
    required: true
  model:
    description: "LLM model name, e.g. 'gpt-4o'"
    required: false
    default: "gpt-4o"
  max_iterations:
    decription: "Maximum number test generation attempts per test file"
    required: false
    default: 3
  desired_coverage:
    description: "Desired coverage percentage"
    required: false
    default: 100

runs:
  using: "composite"
  steps:

    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Run script
      run: |
        ${{ github.action_path }}/scripts/run.sh \
          --pr-number "${{ github.event.pull_request.number }}" \
          --pr-ref "${{ github.event.pull_request.head.ref }}" \
          --project-language "${{ inputs.project_language }}" \
          --project-root "${{ inputs.project_root }}" \
          --code-coverage-report-path "${{ inputs.code_coverage_report_path }}" \
          --test-command "${{ inputs.test_command }}" \
          --model "${{ inputs.model }}" \
          --max-iterations "${{ inputs.max_iterations }}" \
          --desired-coverage "${{ inputs.desired_coverage }}" \
          --action-path "${{ github.action_path }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        <<: ${{ toJSON(env) }}
      shell: bash
